
[base]
base_path = "/opt"
public_url = "https://aki.omusubi.org"

[[apps]]
name = "broinfo"
desc = "A browser information utility."
web = true
[apps.desktop]
linux = true
windows = false
[apps.android]
wva = true
aarch64 = false
x86_64 = false

[[apps]]
name = "cattongue"
desc = "A cat image collection on the web."
web = true
[apps.desktop]
linux = true
windows = false
[apps.android]
wva = true
aarch64 = false
x86_64 = false

[[apps]]
name = "purepic"
desc = "A easy image processing tool."
web = true
[apps.desktop]
linux = true
windows = false
[apps.android]
wva = true
aarch64 = false
x86_64 = false

[[apps]]
name = "pwgen"
desc = "An easy password generator."
web = true
[apps.desktop]
linux = true
windows = false
[apps.android]
wva = true
aarch64 = false
x86_64 = false

[[apps]]
name = "tap3beat"
desc = "A beat viewing tool for beatmania."
web = true
[apps.desktop]
linux = true
windows = false
[apps.android]
wva = true
aarch64 = false
x86_64 = false

[[dev_apps]]
name = "test-inputfile"
desc = "Testing file input functionality."
web = true
[dev_apps.desktop]
linux = true
windows = false
[dev_apps.android]
wva = true
aarch64 = false
x86_64 = false

[[dev_apps]]
name = "test-wasmworker"
desc = "Testing WebAssembly WebWorker."
web = true
[dev_apps.desktop]
linux = true
windows = false
[dev_apps.android]
wva = true
aarch64 = false
x86_64 = false

[[dev_apps]]
name = "test-webworker"
desc = "Testing standard WebWorker."
web = true
[dev_apps.desktop]
linux = true
windows = false
[dev_apps.android]
wva = true
aarch64 = false
x86_64 = false

[[dev_apps]]
name = "memboost"
desc = "Memory booster"
web = true
[dev_apps.desktop]
linux = true
windows = false
[dev_apps.android]
wva = false
aarch64 = true
x86_64 = false

[[dev_apps]]
name = "akiapp"
desc = "Aki's web index page"
web = true
[dev_apps.desktop]
linux = true
windows = false
[dev_apps.android]
wva = true
aarch64 = false
x86_64 = false
